aPhotoADay/Models/DailyPhoto.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace aPhotoADay.Models
{
    public class DailyPhoto
    {
        public Guid Id { get; set; }
        public DateTimeOffset PhotoDate { get; set; }
        public string PhotoPath { get; set; }
        public string Comment { get; set; }
    }
}

aPhotoADay/Models/DailyPhotoViewModel.cs
using System;

namespace aPhotoADay.Models
{
    public class DailyPhotoViewModel
    {
        public DailyPhoto Photo { get; set; }
        public bool HasDailyPhoto { get; set; }
        public DateTimeOffset PhotoDate { get; set; }

        public DailyPhotoViewModel(DailyPhoto[] photoArray, DateTimeOffset photoDate)
        {
            PhotoDate = photoDate;
            if (photoArray.Length > 0)
            {
                Photo = photoArray[0];
                HasDailyPhoto = true;
            }
            else
            {
                HasDailyPhoto = false;
            }
        }

        public bool OnCurrentDay()
        {
            return PhotoDate.Date == DateTimeOffset.Now.Date;
        }

        public string AdjustDateString(double numDays)
        {
            return PhotoDate.AddDays(numDays).ToString("yyyyMMdd");
        }
    }
}

aPhotoADay/Models/ErrorViewModel.cs
using System;

namespace aPhotoADay.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

aPhotoADay/Controllers/DailyPhotoController.cs
using System;
using System.IO;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using aPhotoADay.Services;
using aPhotoADay.Models;
using Microsoft.AspNetCore.Http;
using System.Globalization;

namespace aPhotoADay.Controllers
{
    public class DailyPhotoController : Controller
    {
        private readonly IDailyPhotoService _dailyPhotoService;
        public DailyPhotoController(IDailyPhotoService dailyPhotoService)
        {
            _dailyPhotoService = dailyPhotoService;
        }

        public async Task<IActionResult> Index(string id)
        {
            DateTimeOffset photoDate = DateTimeOffset.ParseExact(id, "yyyyMMdd",CultureInfo.InvariantCulture);
            if (photoDate.Date > DateTimeOffset.Now.Date)
            {
                return RedirectToAction("Index", new { id = DateTimeOffset.Now.ToString("yyyyMMdd") });
            }
            var photoArray = await _dailyPhotoService.GetDailyPhotoAsync(photoDate);

            var model = new DailyPhotoViewModel(photoArray, photoDate);

            return View(model);
        }

        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UploadPhoto(DailyPhoto newPhoto, IFormFile photoFile)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", new { id = newPhoto.PhotoDate.ToString("yyyyMMdd") });
            }

            var successful = await _dailyPhotoService.AddDailyPhotoAsync(newPhoto, photoFile);
            if (!successful)
            {
                return BadRequest("Could not add photo.");
            }
            
            return RedirectToAction("Index", new { id = newPhoto.PhotoDate.ToString("yyyyMMdd") });
        }
    }
}

aPhotoADay/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using aPhotoADay.Models;

namespace aPhotoADay.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

aPhotoADay/Views/DailyPhoto/Index.cshtml
@using aPhotoADay.Models
@model DailyPhotoViewModel

@{
    ViewData["Title"] = "View Your Images";
}

<div class="panel panel-default image-panel">
    <div class="flexContainer">
        <div class="flexItem">
            <p class="text-left">
                <a class="nav-link text-dark" asp-area="" asp-controller="DailyPhoto"
                    asp-action="Index" asp-route-id='@Model.AdjustDateString(-1)'><<</a>
            </p>
        </div>
        <div class="photoView text-center">
            <h2 class="display-5">@Model.PhotoDate.ToString("MMMM d, yyyy")</h2>
            @if (Model.HasDailyPhoto == true)
            {        
                <img style="max-width:400px;" src="@Model.Photo.PhotoPath" alt="@Model.Photo.PhotoPath"
                    asp-append-version="true" />
                <p style="padding-top:10px;">@Model.Photo.Comment</p>

            }
            @if (Model.HasDailyPhoto == false)
            {
                @await Html.PartialAsync("UploadPhotoPartial", new DailyPhoto { PhotoDate = Model.PhotoDate });
            }
        </div>
        <div class="flexItem">
            @if (!Model.OnCurrentDay())
            {
                <p class="text-right">
                    <a class="nav-link text-dark" asp-area="" asp-controller="DailyPhoto"
                        asp-action="Index" asp-route-id='@Model.AdjustDateString(1)'>>></a>
                </p>
            }
        </div>
    </div>

</div>

aPhotoADay/Views/DailyPhoto/UploadPhotoPartial.cshtml
@model DailyPhoto

<form asp-action="UploadPhoto" method="POST" enctype="multipart/form-data">
    <label for="photoFile">Select a photo:</label>
    <input type="file" name="photoFile" accept="image/*" style="margin-bottom: 10px" />
    <br />
    <label asp-for="Comment">Add a comment:</label>
    <input asp-for="Comment">
    <input type="hidden" asp-for="PhotoDate" value="@Model.PhotoDate">
    <br />
    <button type="submit" style="margin-top: 10px">Upload</button>
</form>

aPhotoADay/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p><b>aPhotoADay</b> allows you to save one photo every day.</p>
    <p>Use this to remember the highlights of your days, or watch something you love change over time.</p>
    <p>Some ideas of things to photograph:</P>
    <div class="center-block centerList"><ul class="text-left" style="">
        <li>a child or pet</li>
        <li>scenery while on vacation</li>
        <li>a newly planted garden</li>
        <li>a home improvement project</li>
    </ul></div>
</div>

aPhotoADay/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - aPhotoADay</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">aPhotoADay</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DailyPhoto" asp-action="Index" asp-route-id='@DateTime.Now.ToString("yyyyMMdd")'>Daily Photo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - aPhotoADay - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>